trigger:
  branches:
    include:
      - master  # Aanpassen naar je standaard branch

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'  # Specificeer de versie van Node.js die je wilt gebruiken
  displayName: 'Installeer Node.js'

- script: |
    set -x  # Activeer debug-informatie
    npm install
  displayName: 'Installeer npm-pakketten'

- script: |
    mkdir -p results  # Maak resultatenmap aan voor testresultaten
  displayName: 'Maak resultatenmap aan'

- script: |
    npm run build  # Bouw project (optioneel, als je geen aparte build-stap nodig hebt)
  displayName: 'Bouw project'

- script: |
    npm run test  # Run Cypress tests zonder specifieke reporter-opties
  displayName: 'Voer Cypress-tests uit'
  continueOnError: true  # Taak zal niet falen op foutmeldingen in standaard fout

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/results/*.xml'  # Zoek in de resultatenmap naar eventuele JUnit-uitvoerbestanden van Cypress
    searchFolder: '$(System.DefaultWorkingDirectory)'
    failTaskOnFailedTests: false
